baseURL = "/"
languageCode = "de-de"
title = "Salzburger Orientierungslauf Verband"
theme = "solv"
copyright = "SOLV - Powered by [Hugo](//gohugo.io) and [UIkit](//getuikit.com)"
enableGitInfo = true
ignoreFiles = [ "\\.xml$", "\\.skb$", "\\.foo$"]
paginate = 10

[taxonomies]
    tag = "tags"
    archive = "archives"

[permalinks]
	demo = "/:year/:filename/"
	code = "/:filename/"

[[menu.main]]
    identifier = "blog"
    name = "Kategorie"
    url = "/blog/"
    weight = 10
[[menu.main]]
    identifier = "all"
    name = "Alle"
    url = "/blog/"
    weight = 10
    parent = "blog"
[[menu.main]]
    identifier = "events"
    name = "Veranstaltungen"
    url = "/event/"
    weight = 11
    parent = "blog"
[[menu.main]]
    identifier = "pressinfos"
    name = "Presse"
    url = "/pressinfo/"
    weight = 12
    parent = "blog"
[[menu.main]]
    identifier = "posts"
    name = "Beiträge"
    url = "/post/"
    weight = 13
    parent = "blog"

[[menu.main]]
    identifier = "blog_divider1"
    name = "divider"
    weight = 14
    parent = "blog"

[[menu.main]]
    identifier = "tags"
    name = "Schlagwörter"
    weight = 15
    parent = "blog"

[[menu.main]]
    identifier = "archives"
    name = "Archiv"
    weight = 16
    parent = "blog"

[[menu.main]]
    identifier = "solv"
    name = "Verband"
    url = "/board/"
    weight = 20

[[menu.main]]
    identifier = "solv_divider1"
    name = "divider"
    weight = 199
    parent = "solv"

[[menu.main]]
    identifier = "cup"
    name = "CUPS & LMS"
    url = "/event/"
    weight = 30

[params]
    description = "SOLV website"
	# Date and time formatting, see https://gohugo.io/functions/format/
	time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
	time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700" 
	time_format_default = "Jan 2, 2006"
    time_format_last_mod = "2. Jan 2006 (15:04)"
	time_format_event_daymonth = "2 Jan"
	time_format_event_year = "2006"
    time_format_hhmm = "15:04"
    use_google = false
    num_of_planned_events_preview = 4
    add_invalid_champs = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = false
    tags = true
    tag_cloud = false
    archives = true

[outputs]
    page = ["HTML", "JSON"]
    section = ["HTML", "JSON"]
