baseURL = "https://www.ol-sbg.at"
languageCode = "de-de"
title = "Salzburger Orientierungslauf Verband"
theme = "hugo-solv"
copyright = "SOLV - Powered by [Hugo](//gohugo.io) and [UIkit](//getuikit.com)"
enableGitInfo = true
ignoreFiles = [ "\\.xml$", "\\.skb$", "\\.foo$"]
paginate = 10
buildFuture = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
    tag = "tags"
    archive = "archives"

[permalinks]
	demo = "/:year/:filename/"
	code = "/:filename/"

[[menu.main]]
    identifier = "blog"
    name = "Kategorie"
    url = "/blog/"
    weight = 10
[[menu.main]]
    identifier = "all"
    name = "Alle"
    url = "/blog/"
    weight = 10
    parent = "blog"
[[menu.main]]
    identifier = "events"
    name = "Veranstaltungen"
    url = "/event/"
    weight = 11
    parent = "blog"
[[menu.main]]
    identifier = "pressinfos"
    name = "Presse"
    url = "/pressinfo/"
    weight = 12
    parent = "blog"
[[menu.main]]
    identifier = "posts"
    name = "Beiträge"
    url = "/post/"
    weight = 13
    parent = "blog"

[[menu.main]]
    identifier = "blog_divider1"
    name = ""
    weight = 14
    parent = "blog"
    [menu.main.params]
        class = 'uk-nav-divider'
        type = 'divider'

[[menu.main]]
    identifier = "tags"
    name = "Schlagwörter"
    weight = 15
    parent = "blog"

[[menu.main]]
    identifier = "archives"
    name = "Archiv"
    weight = 16
    parent = "blog"

[[menu.main]]
    identifier = "training"
    name = "Training"
    url = "/training/"
    weight = 20

[[menu.main]]
    identifier = "solv"
    name = "Verband"
    url = "/board/"
    weight = 30

[[menu.main]]
    identifier = "solv_divider1"
    name = ""
    weight = 199
    parent = "solv"
    [menu.main.params]
        class = 'uk-nav-divider'
        type = 'divider'

[[menu.main]]
    identifier = "solv_divider2"
    name = ""
    weight = 298
    parent = "solv"
    [menu.main.params]
        class = 'uk-nav-divider'
        type = 'divider'

[[menu.main]]
    identifier = "legacyweb"
    name = "Alte SOLV website"
    url = "http://old.ol-sbg.at"
    weight = 299
    parent = "solv"

[[menu.main]]
    identifier = "training_divider2"
    name = "Archiv"
    weight = 880
    parent = "training"
    [menu.main.params]
        class = 'uk-nav-header'
        type = 'header'

[[menu.main]]
    identifier = "cup"
    name = "CUPS & LMS"
    url = "/event/"
    weight = 40

[params]
    description = "SOLV website"
    short_title = "SOLV"
	# Date and time formatting, see https://gohugo.io/functions/format/
	time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
	time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700"
	time_format_default = "Jan 2, 2006"
    time_format_last_mod = "2. Jan 2006 (15:04)"
    time_format_ical_date = "20060102"
    time_format_ical_date_time = "20060102T150405"
	time_format_event_daymonth = "2 Jan"
	time_format_event_year = "2006"
    time_format_hhmm = "15:04"
    use_google = false
    num_of_planned_events_preview = 4
    add_invalid_champs = false
    show_hero = false
    link_national_events = "http://www.oefol.at/kuenftige-termine/"
    uikit_version = "3.15.12"

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = false
    categories = false
    tags = true
    tag_cloud = false
    archives = true

[outputs]
    home = ["HTML", "JSON"]
    page = ["HTML"]
    section = ["HTML", "Calendar"]

[outputFormats]
  [outputFormats.result]
    baseName = "resu"
    isPlainText = true
    mediaType = "text/html"
    permalinkable = true
  [outputFormats.splitsbrowser]
    baseName = "splitsbrowser"
    isPlainText = true
    mediaType = "text/html"
    permalinkable = true
  [outputFormats.Calendar]
    protocol = "https://"
    permalinkable = true
