baseURL = "/"
languageCode = "de-de"
title = "Salzburger Orientierungslauf Verband"
theme = "solv-two"
copyright = "SOLV - Powered by [Hugo](//gohugo.io)"
enableGitInfo = true
ignoreFiles = [ "\\.fou$"]

[taxonomies]
    tag = "tags"
    category = "categories"

[permalinks]
	post = "/:year/:month/:filename/"
	code = "/:filename/"

[[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10

[[menu.main]]
    identifier = "solv"
    name = "Verband"
    url = "/about-ol/"
    weight = 20

[[menu.main]]
    identifier = "events"
    name = "CUP & Meisterschaften"
    url = "/event/"
    weight = 30

[[menu.main]]
    identifier = "current-cup"
    name = "Stand Salzburg Cup"
    url = "/event/2017/sbgcup.pdf"
    parent = "events"

[[menu.main]]
    identifier = "current-cup1"
    name = "Stand Salzburg Cup 1"
    url = "/event/2017/rangliste-salzburg-cup-2017"
    parent = "events"

[[menu.main]]
    identifier = "current-cup2"
    name = "Stand Salzburg Cup 2"
    url = "/2017/SbgCup-2017.html"
    parent = "events"

[params]
    description = "SOLV website"
	# Date and time formatting, see https://gohugo.io/functions/format/
	time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
	time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700" 
	time_format_default = "Jan 2, 2006"
    time_format_hhmm = "15:04"
    use_google = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    recent_articles = true
    categories = true
    tags = true
    tag_cloud = true

[outputs]
    page = ["HTML", "JSON"]
    section = ["HTML", "JSON"]
