baseURL = "/"
languageCode = "de-de"
title = "SOLV"
theme = "solv-one"
copyright = "SOLV"


[permalinks]
	post = "/:year/:month/:filename/"
	code = "/:filename/"

[[menu.main]]
    identifier = "post"
    name = "Posts"
    url = "/post/"
    weight = 10

[[menu.main]]
    identifier = "solv"
    name = "SOLV"
    url = "/about/"
    weight = 20

[[menu.main]]
    identifier = "events"
    name = "CUP & Meisterschaften"
    url = "/events/"
    weight = 30

[[menu.main]]
    identifier = "impressum"
    name = "Impressum"
    url = "/impressum/"
    weight = 40

[params]
	# Date and time formatting, see https://gohugo.io/functions/format/
	time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
	time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700" 
	time_format_default = "Jan 2, 2006"